# default_index:
#     path: /
#     defaults: { _controller: "AppBundle:Default:index" }
#     methods: GET

default_autenticacion:
    path: /autenticacion
    defaults: { _controller: "BackendBundle:Default:autenticacion" }
    methods: POST

default_login:
    path: /login
    defaults: { _controller: "BackendBundle:Default:login" }
    methods: POST