user_new:
    path: /new
    defaults: { _controller: "AppBundle:User:new" }
    methods: POST

user_edit:
    path: /edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods: POST

user_list:
    path: /list
    defaults: { _controller: "AppBundle:User:list" }
    methods: POST