default_index:
    path: /
    defaults: { _controller: "FrontendBundle:Default:index" }
    methods: GET

default_login1:
    path: /login-ratsoft
    defaults: { _controller: "FrontendBundle:Default:login" }
    methods: GET

default_register:
    path: /register
    defaults: { _controller: "FrontendBundle:Default:register" }
    methods: GET

home_index:
    path: /home
    defaults: { _controller: "FrontendBundle:Default:home" }
    methods: GET

contable_index:
    path: /contable
    defaults: { _controller: "FrontendBundle:Modulos:contable" } 
                              # bundle, dps controler y funcion que llama 
    methods: GET

impositivo_index:
    path: /impositivo
    defaults: { _controller: "FrontendBundle:Modulos:impositivo" } 
                              # bundle, dps controler y funcion que llama 
    methods: GET

ventas_index:
    path: /ventas
    defaults: { _controller: "FrontendBundle:Ventas:index" } 
                              # bundle, dps controler y funcion que llama 
    methods: GET