BackendBundle\Entity\TblEmpresas:
    type: entity
    table: tbl_empresas
    indexes:
        FK_PROVINCIA_idx:
            columns:
                - provincia
        FK_IVA_idx:
            columns:
                - iva
        FK_RUBRO_idx:
            columns:
                - rubro
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        domicilio:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        localidad:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        cuit:
            type: bigint
            nullable: true
            options:
                unsigned: false
        iibb:
            type: integer
            nullable: true
            options:
                unsigned: false
        titular:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        activo:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        iva:
            targetEntity: TblSituacionIva
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iva:
                    referencedColumnName: id
            orphanRemoval: false
        provincia:
            targetEntity: TblProvincias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                provincia:
                    referencedColumnName: id
            orphanRemoval: false
        rubro:
            targetEntity: TblRubros
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rubro:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
