backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }

backend_default:
  resource: "@BackendBundle/Resources/config/routing/default.yml"
  prefix: /

backend_user:
  resource: "@BackendBundle/Resources/config/routing/user.yml"
  prefix: /user

backend_empresas:
  resource: "@BackendBundle/Resources/config/routing/empresas.yml"
  prefix: /empresa

backend_compras:
  resource: "@BackendBundle/Resources/config/routing/compras.yml"
  prefix: /compras

backend_rubros:
  resource: "@BackendBundle/Resources/config/routing/rubros.yml"
  prefix: /rubros

backend_provincias:
  resource: "@BackendBundle/Resources/config/routing/provincias.yml"
  prefix: /provincias

backend_iva:
  resource: "@BackendBundle/Resources/config/routing/iva.yml"
  prefix: /iva